"""empty message

Revision ID: 639c7c864723
Revises: f45c6bfaae40
Create Date: 2023-09-24 11:52:25.184318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639c7c864723'
down_revision = 'f45c6bfaae40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
